version = 1

exclude_patterns = ["database_utilities_gui.py"]

[[analyzers]]
name = "javascript"
  [analyzers.meta]
  environment = ["jquery"]

[[analyzers]]
name = "python"
  [analyzers.meta]
  runtime_version = "3.x.x"

[[transformers]]
name = "autopep8"