version = 1

[[analyzers]]
name = "javascript"
  [analyzers.meta]
  environment = ["jquery"]

[[analyzers]]
name = "python"
  [analyzers.meta]
  runtime_version = "3.x.x"
  exclude_patterns = [
    "database_utilities_gui.py"
  ]

[[transformers]]
name = "autopep8"